markdown: kramdown
kramdown:
    use_coderay: true
    coderay:
        coderay_line_numbers: table
        coderay_css: class
permalink: /:year/:month/:title/
url: http://xukuang.github.io/blog
author: Xu Kuang


